<?
$term = $_GET[ "term" ];
$companies = array(
	array( "label" => "AUTOMOBILE CLUB INTER-INSURANCE EXCHANGE", "value" => "1" ),
	array( "label" => "AMERICAN FAMILY MUTUAL INSURANCE COMPANY", "value" => "2" ),
	array( "label" => "BANKERS STANDARD INSURANCE COMPANY", "value" => "3" ),
	array( "label" => "FARM BUREAU PROPERTY & CASUALTY INSURANC", "value" => "4" ),
	array( "label" => "FARMERS INSURANCE COMPANY, INC.", "value" => "5" ),
	array( "label" => "PROGRESSIVE DIRECT INSURANCE COMPANY", "value" => "6" ),
	array( "label" => "STATE FARM MUTUAL AUTOMOBILE INSURANCE C", "value" => "7" ),
	array( "label" => "AUTO CLUB FAMILY INSURANCE COMPANY", "value" => "8" ),
	array( "label" => "21st Century Premier Insurance Company", "value" => "9" ),
	array( "label" => "ACE AMERICAN INSURANCE COMPANY", "value" => "10" ),
	array( "label" => "ACE FIRE UNDERWRITERS INSURANCE COMPANY", "value" => "11" ),
	array( "label" => "ACE PROPERTY AND CASUALTY INSURANCE COMP", "value" => "12" ),
	array( "label" => "ADDISON INSURANCE COMPANY", "value" => "13" ),
	array( "label" => "ALLIANCE FOR NONPROFITS", "value" => "14" ),
	array( "label" => "ALLIANCE INDEMNITY COMPANY", "value" => "15" ),
	array( "label" => "ALLIANCE INSURANCE COMPANY, INC.", "value" => "16" ),
	array( "label" => "ALLIED GROUP", "value" => "17" ),
	array( "label" => "ALLSTATE FIRE AND CASUALTY INSURANCE COM", "value" => "18" ),
	array( "label" => "ALLSTATE INDEMNITY COMPANY", "value" => "19" ),
	array( "label" => "ALLSTATE INSURANCE COMPANY", "value" => "20" ),
	array( "label" => "ALLSTATE PROPERTY AND CASUALTY INSURANCE", "value" => "21" ),
	array( "label" => "AMCO INSURANCE COMPANY", "value" => "22" ),
	array( "label" => "american alternative insurance co", "value" => "23" ),
	array( "label" => "AMERICAN AUTOMOBILE INSURANCE COMPANY", "value" => "24" ),
	array( "label" => "AMERICAN CASUALTY COMPANY OF READING, PE", "value" => "25" ),
	array( "label" => "AMERICAN ECONOMY INSURANCE COMPANY", "value" => "26" ),
	array( "label" => "American Family Home Insurance Company", "value" => "27" ),
	array( "label" => "AMERICAN FAMILY MUTUAL INSURANCE COMPANY", "value" => "28" ),
	array( "label" => "AMERICAN FIRE AND CASUALTY COMPANY", "value" => "29" ),
	array( "label" => "AMERICAN GUARANTEE AND LIABILITY INSURAN", "value" => "30" ),
	array( "label" => "AMERICAN INSURANCE COMPANY (THE)", "value" => "31" ),
	array( "label" => "AMERICAN MODERN HOME INSURANCE COMPANY", "value" => "32" ),
	array( "label" => "AMERICAN MODERN SELECT INSURANCE COMPANY", "value" => "33" ),
	array( "label" => "AMERICAN NATIONAL GENERAL INSURANCE COMP", "value" => "34" ),
	array( "label" => "AMERICAN NATIONAL PROPERTY AND CASUALTY", "value" => "35" ),
	array( "label" => "American Service Insurance Co", "value" => "36" ),
	array( "label" => "American Southern Home Insurance Comapny", "value" => "37" ),
	array( "label" => "American Southern Home Insurance Company", "value" => "38" ),
	array( "label" => "AMERICAN STANDARD INSURANCE COMPANY OF W", "value" => "39" ),
	array( "label" => "AMERICAN STATES INSURANCE COMPANY", "value" => "40" ),
	array( "label" => "AMERICAN ZURICH INSURANCE COMPANY", "value" => "41" ),
	array( "label" => "AMERISURE INSURANCE COMPANY", "value" => "42" ),
	array( "label" => "AMERISURE MUTUAL INSURANCE COMPANY", "value" => "43" ),
	array( "label" => "AMERISURE PARTNERS INSURANCE COMPANY", "value" => "44" ),
	array( "label" => "AMICA MUTUAL INSURANCE COMPANY", "value" => "45" ),
	array( "label" => "APPLIED RISK SOLUTIONS", "value" => "46" ),
	array( "label" => "Arch Insurance Company", "value" => "47" ),
	array( "label" => "ARGONAUT MIDWEST INSURANCE", "value" => "48" ),
	array( "label" => "Associated Indemnity Corporation", "value" => "49" ),
	array( "label" => "ASSURANCE COMPANY OF AMERICA", "value" => "50" ),
	array( "label" => "AUTO-OWNERS (MUTUAL) INSURANCE COMPANY", "value" => "51" ),
	array( "label" => "AXIS INSURANCE COMPANY", "value" => "52" ),
	array( "label" => "BANKERS STANDARD INSURANCE COMPANY", "value" => "53" ),
	array( "label" => "Berkley National Ins Co", "value" => "54" ),
	array( "label" => "Berkley Regional Insurance Company", "value" => "55" ),
	array( "label" => "BERKSHIRE HATHAWAY HOMESTATE INSURANCE C", "value" => "56" ),
	array( "label" => "BITUMINOUS CASUALTY CORPORATION", "value" => "57" ),
	array( "label" => "BRISTOL WEST INSURANCE COMPANY", "value" => "58" ),
	array( "label" => "CALIFORNIA CASUALTY INDEMNITY EXCHANGE", "value" => "59" ),
	array( "label" => "Canal Insurance Co", "value" => "60" ),
	array( "label" => "CASTLEPOINT NATIONAL INSURANCE COMPANY", "value" => "61" ),
	array( "label" => "CHARTER OAK FIRE INSURANCE COMPANY (THE)", "value" => "62" ),
	array( "label" => "CHARTIS PROPERTY CASUALTY COMPANY", "value" => "63" ),
	array( "label" => "CHUBB NATIONAL INSURANCE COMPANY", "value" => "64" ),
	array( "label" => "CHURCH MUTUAL INSURANCE COMPANY", "value" => "65" ),
	array( "label" => "CINCINNATI CASUALTY COMPANY (THE)", "value" => "66" ),
	array( "label" => "CINCINNATI INDEMNITY COMPANY (THE)", "value" => "67" ),
	array( "label" => "CINCINNATI INSURANCE COMPANY (THE)", "value" => "68" ),
	array( "label" => "Citizens Insurance Company of America", "value" => "69" ),
	array( "label" => "COLUMBIA MUTUAL INSURANCE COMPANY", "value" => "70" ),
	array( "label" => "COLUMBIA NATIONAL INSURANCE COMPANY", "value" => "71" ),
	array( "label" => "COMMERCE AND INDUSTRY INSURANCE COMPANY", "value" => "72" ),
	array( "label" => "COMPANION PROPERTY AND CASUALTY INSURANC", "value" => "73" ),
	array( "label" => "CONTINENTAL CASUALTY COMPANY", "value" => "74" ),
	array( "label" => "CONTINENTAL INSURANCE COMPANY (THE)", "value" => "75" ),
	array( "label" => "CONTINENTAL WESTERN INSURANCE COMPANY", "value" => "76" ),
	array( "label" => "COUNTRY CASUALTY INSURANCE COMPANY", "value" => "77" ),
	array( "label" => "COUNTRY MUTUAL INSURANCE COMPANY", "value" => "78" ),
	array( "label" => "COUNTRY PREFERRED INSURANCE COMPANY", "value" => "79" ),
	array( "label" => "CRUM & FORSTER INDEMNITY COMPANY", "value" => "80" ),
	array( "label" => "CUMIS INS", "value" => "81" ),
	array( "label" => "DAIRYLAND INSURANCE COMPANY", "value" => "82" ),
	array( "label" => "DELOS INSURANCE", "value" => "83" ),
	array( "label" => "DEPOSITORS INSURANCE COMPANY", "value" => "84" ),
	array( "label" => "Discover Property and Casualty", "value" => "85" ),
	array( "label" => "ELECTRIC INSURANCE COMPANY", "value" => "86" ),
	array( "label" => "EMCASCO INSURANCE COMPANY", "value" => "87" ),
	array( "label" => "EMPIRE FIRE AND MARINE INSURANCE COMPANY", "value" => "88" ),
	array( "label" => "EMPLOYERS INSURANCE COMPANY OF WAUSAU", "value" => "89" ),
	array( "label" => "EMPLOYERS MUTUAL CASUALTY COMPANY", "value" => "90" ),
	array( "label" => "ENCOMPASS HOME AND AUTO INSURANCE COMPAN", "value" => "91" ),
	array( "label" => "ENCOMPASS INDEMNITY COMPANY", "value" => "92" ),
	array( "label" => "ENCOMPASS INSURANCE COMPANY OF AMERICA", "value" => "93" ),
	array( "label" => "ESSENTIA INSURANCE COMPANY", "value" => "94" ),
	array( "label" => "EVEREST NATIONAL INSURANCE COMPANY", "value" => "95" ),
	array( "label" => "FARM BUREAU PROPERTY & CASUALTY INSURANC", "value" => "96" ),
	array( "label" => "FARMERS ALLIANCE MUTUAL INSURANCE COMPAN", "value" => "97" ),
	array( "label" => "FARMERS INSURANCE COMPANY, INC.", "value" => "98" ),
	array( "label" => "FARMLAND MUTUAL INSURANCE COMPANY", "value" => "99" ),
	array( "label" => "FEDERAL INSURANCE COMPANY", "value" => "100" ),
	array( "label" => "FIREMAN'S FUND INSURANCE COMPANY", "value" => "101" ),
	array( "label" => "FIRST LIBERTY INSURANCE CORPORATION (THE", "value" => "102" ),
	array( "label" => "FIRST NATIONAL INSURANCE COMPANY OF AMER", "value" => "103" ),
	array( "label" => "FLORISTS' MUTUAL INSURANCE COMPANY", "value" => "104" ),
	array( "label" => "FOREMOST INSURANCE COMPANY", "value" => "105" ),
	array( "label" => "FOREMOST PROPERTY AND CASUALTY INSURANCE", "value" => "106" ),
	array( "label" => "GARRISON PROPERTY AND CASUALTY INSURANCE", "value" => "107" ),
	array( "label" => "Geico Advantage Company", "value" => "108" ),
	array( "label" => "GEICO CASUALTY COMPANY", "value" => "109" ),
	array( "label" => "GEICO GENERAL INSURANCE COMPANY", "value" => "110" ),
	array( "label" => "GEICO INDEMNITY COMPANY", "value" => "111" ),
	array( "label" => "GENERAL CASUALTY COMPANY OF WISCONSIN", "value" => "112" ),
	array( "label" => "GENERAL INSURANCE COMPANY OF AMERICA", "value" => "113" ),
	array( "label" => "GOODVILLE MUTUAL CASUALTY COMPANY", "value" => "114" ),
	array( "label" => "GOVERNMENT EMPLOYEES INSURANCE COMPANY", "value" => "115" ),
	array( "label" => "GRANITE STATE INSURANCE COMPANY", "value" => "116" ),
	array( "label" => "GREAT AMERICAN ALLIANCE INSURANCE COMPAN", "value" => "117" ),
	array( "label" => "GREAT AMERICAN ASSURANCE COMPANY", "value" => "118" ),
	array( "label" => "GREAT AMERICAN INSURANCE COMPANY", "value" => "119" ),
	array( "label" => "GREAT AMERICAN INSURANCE COMPANY OF NEW", "value" => "120" ),
	array( "label" => "Great Divide Insurance Co", "value" => "121" ),
	array( "label" => "GREAT NORTHERN INSURANCE COMPANY", "value" => "122" ),
	array( "label" => "GREENWICH INSURANCE COMPANY", "value" => "123" ),
	array( "label" => "GUIDEONE MUTUAL INSURANCE COMPANY", "value" => "124" ),
	array( "label" => "Hallmark County Mutual Insurance Company", "value" => "125" ),
	array( "label" => "HALLMARK INS CO", "value" => "126" ),
	array( "label" => "HALLMARK NATIONAL INSURANCE COMPANY", "value" => "127" ),
	array( "label" => "Hanover Ins Group Inc (The)", "value" => "128" ),
	array( "label" => "HARCO NATIONAL INSURANCE COMPANY", "value" => "129" ),
	array( "label" => "HARTFORD ACCIDENT AND INDEMNITY COMPANY", "value" => "130" ),
	array( "label" => "HARTFORD CASUALTY INSURANCE COMPANY", "value" => "131" ),
	array( "label" => "HARTFORD FIRE INSURANCE COMPANY", "value" => "132" ),
	array( "label" => "HARTFORD INSURANCE COMPANY OF THE MIDWES", "value" => "133" ),
	array( "label" => "HARTFORD UNDERWRITERS INSURANCE COMPANY", "value" => "134" ),
	array( "label" => "HAWKEYE-SECURITY INSURANCE COMPANY", "value" => "135" ),
	array( "label" => "HDI-GERLING AMERICA INSURANCE COMPANY", "value" => "136" ),
	array( "label" => "HORACE MANN INSURANCE COMPANY", "value" => "137" ),
	array( "label" => "HORACE MANN PROPERTY & CASUALTY INSURANC", "value" => "138" ),
	array( "label" => "IDS PROPERTY CASUALTY INSURANCE COMPANY", "value" => "139" ),
	array( "label" => "ILLINOIS NATIONAL INSURANCE COMPANY", "value" => "140" ),
	array( "label" => "INDEMNITY INSURANCE COMPANY OF NORTH AME", "value" => "141" ),
	array( "label" => "INDIANA LUMBERMENS MUTUAL INSURANCE COMP", "value" => "142" ),
	array( "label" => "INSURANCE COMPANY OF THE STATE OF PENNSY", "value" => "143" ),
	array( "label" => "IRONSHORE INDEMNITY INC.", "value" => "144" ),
	array( "label" => "KEMPER DIRECT INSURANCE", "value" => "145" ),
	array( "label" => "KEMPER INDEPENDENCE INSURANCE COMPANY", "value" => "146" ),
	array( "label" => "LIBERTY INSURANCE CORPORATION", "value" => "147" ),
	array( "label" => "LIBERTY INSURANCE UNDERWRITERS INC", "value" => "148" ),
	array( "label" => "LIBERTY MUTUAL FIRE INSURANCE COMPANY", "value" => "149" ),
	array( "label" => "LIBERTY MUTUAL INSURANCE COMPANY", "value" => "150" ),
	array( "label" => "LM General Insurance Company", "value" => "151" ),
	array( "label" => "LM INSURANCE CORPORATION", "value" => "152" ),
	array( "label" => "MARKEL AMERICAN INSURANCE COMPANY", "value" => "153" ),
	array( "label" => "MARKEL INSURANCE COMPANY", "value" => "154" ),
	array( "label" => "MARYLAND CASUALTY COMPANY", "value" => "155" ),
	array( "label" => "Massachusetts Bay Ins Co", "value" => "156" ),
	array( "label" => "MERASTAR INSURANCE COMPANY", "value" => "157" ),
	array( "label" => "MERIDIAN SECURITY INSURANCE COMPANY", "value" => "158" ),
	array( "label" => "MetLife Auto & Home", "value" => "159" ),
	array( "label" => "Metropolitan Casualty Insurance Company", "value" => "160" ),
	array( "label" => "METROPOLITAN GROUP PROPERTY AND CASUALTY", "value" => "161" ),
	array( "label" => "Metropolitan Property and Casualty Insurance Company", "value" => "162" ),
	array( "label" => "Mid Continent Group", "value" => "163" ),
	array( "label" => "Mid Continent Group Ins Co", "value" => "164" ),
	array( "label" => "MID-CENTURY INSURANCE COMPANY", "value" => "165" ),
	array( "label" => "Missouri Auto Insurance", "value" => "166" ),
	array( "label" => "NATIONAL CASUALTY COMPANY", "value" => "167" ),
	array( "label" => "national continental", "value" => "168" ),
	array( "label" => "NATIONAL FARMERS UNION PROPERTY AND CASU", "value" => "169" ),
	array( "label" => "NATIONAL FIRE INSURANCE COMPANY OF HARTF", "value" => "170" ),
	array( "label" => "NATIONAL GENERAL ASSURANCE COMPANY", "value" => "171" ),
	array( "label" => "NATIONAL GENERAL INSURANCE COMPANY", "value" => "172" ),
	array( "label" => "NATIONAL INDEMNITY COMPANY", "value" => "173" ),
	array( "label" => "NATIONAL INTERSTATE INSURANCE COMPANY", "value" => "174" ),
	array( "label" => "NATIONAL SURETY CORPORATION", "value" => "175" ),
	array( "label" => "NATIONAL UNION FIRE INSURANCE COMPANY OF", "value" => "176" ),
	array( "label" => "NATIONWIDE AFFINITY INSURANCE COMPANY OF", "value" => "177" ),
	array( "label" => "NATIONWIDE AGRIBUSINESS INSURANCE COMPAN", "value" => "178" ),
	array( "label" => "NATIONWIDE INSURANCE COMPANY OF AMERICA", "value" => "179" ),
	array( "label" => "NATIONWIDE MUTUAL INSURANCE COMPANY", "value" => "180" ),
	array( "label" => "NAVIGATORS INSURANCE COMPANY", "value" => "181" ),
	array( "label" => "NEW HAMPSHIRE INSURANCE COMPANY", "value" => "182" ),
	array( "label" => "NORTH RIVER INSURANCE COMPANY (THE)", "value" => "183" ),
	array( "label" => "NORTHERN INSURANCE COMPANY OF NEW YORK", "value" => "184" ),
	array( "label" => "Nova Casualty Company", "value" => "185" ),
	array( "label" => "OAK RIVER INSURANCE COMPANY", "value" => "186" ),
	array( "label" => "OHIO CASUALTY INSURANCE COMPANY (THE)", "value" => "187" ),
	array( "label" => "Ohio Security Insurance", "value" => "188" ),
	array( "label" => "OLD REPUBLIC GENERAL INSURANCE CORPORATI", "value" => "189" ),
	array( "label" => "OWNERS INSURANCE COMPANY", "value" => "190" ),
	array( "label" => "PACIFIC INDEMNITY COMPANY", "value" => "191" ),
	array( "label" => "PACIFIC SPECIALTY", "value" => "192" ),
	array( "label" => "PENN MILLERS INSURANCE COMPANY", "value" => "193" ),
	array( "label" => "PHARMACISTS MUTUAL INSURANCE COMPANY", "value" => "194" ),
	array( "label" => "PHILADELPHIA INDEMNITY INSURANCE COMPANY", "value" => "195" ),
	array( "label" => "PHOENIX INSURANCE COMPANY (THE)", "value" => "196" ),
	array( "label" => "PLAZA INSURANCE COMPANY", "value" => "197" ),
	array( "label" => "PRAETORIAN INSURANCE COMPANY", "value" => "198" ),
	array( "label" => "PREFERRED PROFESSIONAL INSURANCE COMPANY", "value" => "199" ),
	array( "label" => "Privilege Underwriters Reciprocal Exchange", "value" => "200" ),
	array( "label" => "PROGRESSIVE DIRECT INSURANCE COMPANY", "value" => "201" ),
	array( "label" => "Progressive Insurance Company", "value" => "202" ),
	array( "label" => "PROGRESSIVE NORTHWESTERN INSURANCE COMPA", "value" => "203" ),
	array( "label" => "PROPERTY AND CASUALTY INSURANCE COMPANY", "value" => "204" ),
	array( "label" => "PROTECTIVE INSURANCE COMPANY", "value" => "205" ),
	array( "label" => "QBE INSURANCE CORPORATION", "value" => "206" ),
	array( "label" => "REGENT INSURANCE COMPANY", "value" => "207" ),
	array( "label" => "RIVERPORT INSURANCE COMPANY", "value" => "208" ),
	array( "label" => "RLI Insurance Corporation", "value" => "209" ),
	array( "label" => "SAFE AUTO INSURANCE COMPANY", "value" => "210" ),
	array( "label" => "SAFECO INSURANCE COMPANY OF AMERICA", "value" => "211" ),
	array( "label" => "SAFECO INSURANCE COMPANY OF ILLINOIS", "value" => "212" ),
	array( "label" => "SAGAMORE INSURANCE COMPANY", "value" => "213" ),
	array( "label" => "SCOTTSDALE INDEMNITY COMPANY", "value" => "214" ),
	array( "label" => "SENTINEL INSURANCE COMPANY, LTD.", "value" => "215" ),
	array( "label" => "SENTRY CASUALTY COMPANY", "value" => "216" ),
	array( "label" => "SENTRY INSURANCE A MUTUAL COMPANY", "value" => "217" ),
	array( "label" => "SENTRY SELECT INSURANCE COMPANY", "value" => "218" ),
	array( "label" => "SHELTER GENERAL INSURANCE COMPANY", "value" => "219" ),
	array( "label" => "SHELTER MUTUAL INSURANCE COMPANY", "value" => "220" ),
	array( "label" => "Southern Insurance Company", "value" => "221" ),
	array( "label" => "SPARTA INSURANCE COMPANY", "value" => "222" ),
	array( "label" => "ST. PAUL FIRE & MARINE INSURANCE COMPANY", "value" => "223" ),
	array( "label" => "STATE AUTO PROPERTY AND CASUALTY INSURAN", "value" => "224" ),
	array( "label" => "STATE AUTOMOBILE MUTUAL INSURANCE COMPAN", "value" => "225" ),
	array( "label" => "STATE FARM FIRE AND CASUALTY COMPANY", "value" => "226" ),
	array( "label" => "STATE FARM MUTUAL AUTOMOBILE INSURANCE C", "value" => "227" ),
	array( "label" => "TEACHERS INSURANCE COMPANY", "value" => "228" ),
	array( "label" => "TOPA INSURANCE COMPANY", "value" => "229" ),
	array( "label" => "TOWER NATIONAL INSURANCE COMPANY", "value" => "230" ),
	array( "label" => "TRADERS INSURANCE COMPANY", "value" => "231" ),
	array( "label" => "TRANSGUARD INSURANCE COMPANY OF AMERICA,", "value" => "232" ),
	array( "label" => "TRANSPORTATION INSURANCE COMPANY", "value" => "233" ),
	array( "label" => "TRAVELERS CASUALTY INSURANCE COMPANY OF", "value" => "234" ),
	array( "label" => "TRAVELERS COMMERCIAL INSURANCE COMPANY", "value" => "235" ),
	array( "label" => "TRAVELERS HOME AND MARINE INSURANCE COMP", "value" => "236" ),
	array( "label" => "TRAVELERS INDEMNITY COMPANY (THE)", "value" => "237" ),
	array( "label" => "TRAVELERS INDEMNITY COMPANY OF AMERICA (", "value" => "238" ),
	array( "label" => "TRAVELERS INDEMNITY COMPANY OF CONNECTIC", "value" => "239" ),
	array( "label" => "TRAVELERS PROPERTY CASUALTY COMPANY OF A", "value" => "240" ),
	array( "label" => "TRIANGLE INSURANCE COMPANY, INC.", "value" => "241" ),
	array( "label" => "TRIUMPHE CASUALTY COMPANY", "value" => "242" ),
	array( "label" => "TWIN CITY FIRE INSURANCE COMPANY", "value" => "243" ),
	array( "label" => "UNION INSURANCE COMPANY", "value" => "244" ),
	array( "label" => "UNION INSURANCE COMPANY OF PROVIDENCE", "value" => "245" ),
	array( "label" => "UNITED FINANCIAL CASUALTY COMPANY", "value" => "246" ),
	array( "label" => "UNITED FIRE AND CASUALTY COMPANY", "value" => "247" ),
	array( "label" => "UNITED SERVICES AUTOMOBILE ASSOCIATION", "value" => "248" ),
	array( "label" => "UNITED STATES FIRE INSURANCE COMPANY", "value" => "249" ),
	array( "label" => "USAA CASUALTY INSURANCE COMPANY", "value" => "250" ),
	array( "label" => "USAA GENERAL INDEMNITY COMPANY", "value" => "251" ),
	array( "label" => "VALLEY FORGE INSURANCE COMPANY", "value" => "252" ),
	array( "label" => "VANLINER INSURANCE COMPANY", "value" => "253" ),
	array( "label" => "VICTORIA FIRE & CASUALTY COMPANY", "value" => "254" ),
	array( "label" => "VIGILANT INSURANCE COMPANY", "value" => "255" ),
	array( "label" => "WAUSAU BUSINESS INSURANCE COMPANY", "value" => "256" ),
	array( "label" => "WAUSAU UNDERWRITERS INSURANCE COMPANY", "value" => "257" ),
	array( "label" => "WESCO INSURANCE COMPANY", "value" => "258" ),
	array( "label" => "WEST AMERICAN INSURANCE COMPANY", "value" => "259" ),
	array( "label" => "WESTERN AGRICULTURAL INSURANCE COMPANY", "value" => "260" ),
	array( "label" => "WESTERN UNITED INSURANCE COMPANY", "value" => "261" ),
	array( "label" => "WESTFIELD INSURANCE COMPANY", "value" => "262" ),
	array( "label" => "WILSHIRE INSURANCE COMPANY", "value" => "263" ),
	array( "label" => "XL INSURANCE AMERICA, INC.", "value" => "264" ),
	array( "label" => "XL SPECIALTY INSURANCE COMPANY", "value" => "265" ),
	array( "label" => "ZURICH AMERICAN INSURANCE COMPANY", "value" => "266" ),
	array( "label" => "ZURICH AMERICAN INSURANCE COMPANY OF ILL", "value" => "267" ),
	array( "label" => "AUTO CLUB FAMILY INSURANCE COMPANY", "value" => "268" ),
	array( "label" => "STATE FARM FIRE AND CASUALTY COMPANY", "value" => "269" )
);

$result = array();
foreach ($companies as $company) {
	$companyLabel = $company[ "label" ];
	if ( strpos( strtoupper($companyLabel), strtoupper($term) )
	  !== false ) {
		array_push( $result, $company );
	}
}

echo json_encode( $result );
?>